version: '3'

services:
  backend:
    container_name: db
    build: ./backend
    ports:
      - 3001:3001
  frontend:
    container_name: front
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 3000:80
    environment:
    - teste=test